services:
  backend:
    image: 426857564226.dkr.ecr.us-east-1.amazonaws.com/anish-docker-backend:latest
    ports:
      - 3000:3000

  frontend:
    image: 426857564226.dkr.ecr.us-east-1.amazonaws.com/anish-docker-frontend:latest
    ports:
      - 8001:80

  database:
    image: 426857564226.dkr.ecr.us-east-1.amazonaws.com/anish-docker-database:latest
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: appdb

volumes:
  dbvolume: